[package]
name = "stemma"
version.workspace = true
edition.workspace = true
description = "The Stemma command line"
license.workspace = true

[[bin]]
name = "stemma"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive", "env"] }
cliclack = "0.5.6"
indicatif = "0.18.6"
minijinja = { version = "2.24.0", features = ["json"] }
owo-colors = { version = "4.4.0", features = ["supports-colors"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"
toml_edit = "0.25.15"
